const programs=[
 {n:'01',title:'Traditional Medicare',tag:'ACO REACH · LEAD · MSSP',text:'Support complete documentation, proactive gap closure and coordinated care across ACO REACH, LEAD and MSSP fee-for-service populations.'},
 {n:'02',title:'Medicare Advantage',text:'Bring risk, quality and coding priorities into the encounter to support stronger plan and provider performance.'},
 {n:'03',title:'Medicaid Managed Care',text:'Help managed Medicaid plans and their network providers close quality and risk gaps while coordinating care for enrolled members.'},
];
const sidecar=[
 ['Ambient listening','Uses AI to listen to the encounter and generate a clinical summary note, without pulling the provider away from the patient.'],
 ['RAF recapture','Surfaces supported risk-adjustment (RAF) recapture opportunities at the point of care.'],
 ['Gap closure','Guides the provider toward open care and quality actions during the visit.'],
 ['ICD & CPT support','AI-suggested ICD and CPT coding, always left for clinician review and confirmation.'],
 ['MEAT alignment','Prompts for complete, defensible documentation — Monitor, Evaluate, Assess and Treat — in the encounter.'],
 ['Real-time write-back','Returns reviewed documentation, codes and actions directly to the EHR.'],
];
const command=[
 ['Retrospective analytics','See unresolved issues, trends and performance across populations, providers and contracts.'],
 ['Issue identification','Find the recapture, quality, coding and scheduling opportunities that need attention.'],
 ['Work management','Assign, prioritize and follow opportunities from identification through closure.'],
 ['Scheduling assistance','Bring the right patients back at the right time based on clinical and value-based priorities.'],
];
export default function Home(){return <main>
 <section className="hero shell" id="top"><div className="tag"><i/> Encounter intelligence for value-based care</div><h1>Identify the issue.<br/><em>Close it in care.</em></h1><div className="hero-foot"><p>Vediq connects a retrospective command center with an AI-powered point-of-care sidecar—helping providers, ACOs and managed care organizations surface, guide and close the issues that drive value-based performance.</p><a className="round" href="#system">↓</a></div></section>
 <section className="dark-band"><div className="shell band-grid"><p>One closed loop from population insight to completed action.</p><div><span>01</span><strong>Identify</strong><small>Command center</small></div><div><span>02</span><strong>Close</strong><small>Clinical sidecar</small></div><div><span>03</span><strong>Improve</strong><small>Value-based performance</small></div></div></section>
 <section className="section shell" id="system"><div className="intro"><span>How Vediq works</span><h2>Two connected products.<br/>One performance loop.</h2><p>The command center is a retrospective, population-health-style analytics and work-management view for ACO, plan and practice leaders. The sidecar is an ambient, AI-listening assistant that runs during the encounter itself, guiding completion and writing the result back to the EHR.</p></div><div className="loop"><article><b>01</b><small>Command center</small><h3>See what needs attention.</h3><p>Retrospective analytics surface issues across the population and help teams prioritize the work.</p></article><i>→</i><article className="accent"><b>02</b><small>Sidecar</small><h3>Resolve it at the encounter.</h3><p>Ambient intelligence guides the provider through recapture, gap closure, coding and documentation.</p></article><i>→</i><article><b>03</b><small>EHR + command center</small><h3>Complete the record.</h3><p>Clinician-reviewed data returns to the EHR in real time and updates the management view.</p></article></div></section>
 <section className="blue section" id="sidecar"><div className="shell"><div className="intro light"><span>Point-of-care sidecar</span><h2>Close the opportunity<br/>while care is happening.</h2><p>Vediq runs alongside the encounter, giving providers timely guidance without turning the visit into another administrative workflow. We'll walk through exactly how it fits into your exam room in a live demo. In practice: it listens, drafts the note, and quietly surfaces a supported recapture opportunity, an open gap and a suggested code — all left for the provider to confirm before anything is filed.</p></div><div className="feature-grid">{sidecar.map((x,i)=><article key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>
 <section className="section shell" id="command"><div className="intro"><span>Management command center</span><h2>Find the issues.<br/>Manage the work.</h2><p>A retrospective operating view for ACO, plan and provider leaders to understand performance, coordinate action and prepare future encounters. In practice: leadership sees a prioritized list of open issues, assigns and tracks them by practice or provider, and knows the moment they're resolved at the next encounter. Built on EHR and payer claims data live today, with HIE and ADT feed integration already built in and ready to connect as new sources come online.</p></div><div className="command-grid">{command.map((x,i)=><article key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section>
 <section className="ink section" id="programs"><div className="shell"><div className="intro light"><span>Programs supported</span><h2>Built for the Medicare<br/>value-based landscape.</h2><p>Vediq supports providers, ACOs and managed care organizations across three core value-based environments, adapting encounter guidance and management priorities to the work that matters in each.</p></div><div className="program-grid">{programs.map(p=><article key={p.n}><span>{p.n}</span><h3>{p.title}</h3>{p.tag&&<small>{p.tag}</small>}<p>{p.text}</p></article>)}</div></div></section>
 <section className="section shell audience"><div className="intro"><span>Who Vediq serves</span><h2>Designed for the people<br/>accountable for outcomes.</h2></div><div className="audience-grid"><article><small>Providers</small><h3>Stay focused on the patient.</h3><p>Receive the right guidance during the encounter, review the result and complete the record without duplicate work.</p></article><article><small>ACOs &amp; MCOs</small><h3>Turn insight into closed action.</h3><p>Identify issues across the population, manage priorities across practices and networks, and see whether opportunities are resolved.</p></article></div></section>
 <section className="section shell" id="who-we-are"><div className="intro"><span>Who we are</span><h2>Built to close the<br/>loop, not just find it.</h2><p>Identifying a gap, a recapture opportunity or a coding issue is not the hard part of value-based care. Closing it — inside a real encounter, without adding to a provider&apos;s workload — is. Vediq is built around that closing step.</p></div></section>
 <section className="closing shell"><span>See Vediq in action</span><h2>Move from identified<br/><em>to completed.</em></h2><div><p>See how Vediq helps providers, ACOs and managed care organizations close value-based opportunities inside the clinical encounter.</p><a className="button lime" href="/demo">Request a demo <b>↗</b></a></div></section>
 </main>}
